//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class BattleManager : MonoBehaviour
		{

		Commander lCommander;
		Commander rCommander;
		Biome biome;
		bool isDay;

		void Start () {
			lCommander = GameObject.Find<Player> ()
		}
		
		// Update is called once per frame
		void Update () {
			
		}
		}
}

